In [1]:
import numpy as np

In [2]:
my_list1 = [23,4,67,56,40,38,70,100,99,77,44,33,45]

In [11]:
my_list2 = [11,22,33,44,55,66,77,88,99,199,111,122,133]

In [12]:
#creating an array from a list
array1 = np.array(my_list1)

In [13]:
array1

array([ 23,   4,  67,  56,  40,  38,  70, 100,  99,  77,  44,  33,  45])

In [14]:
tot_list = [my_list1,my_list2]

In [15]:
tot_list

[[23, 4, 67, 56, 40, 38, 70, 100, 99, 77, 44, 33, 45],
 [11, 22, 33, 44, 55, 66, 77, 88, 99, 199, 111, 122, 133]]

In [16]:
array2 =np.array(tot_list)

In [17]:
array2

array([[ 23,   4,  67,  56,  40,  38,  70, 100,  99,  77,  44,  33,  45],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 199, 111, 122, 133]])

In [20]:
array2.shape
#gives the shape of the array

(2, 13)

In [22]:
#we can check the datatype of the array as well by using 'dtype'
array2.dtype


dtype('int64')

In [25]:
#thus we created multi dimensional array from lists..
#now there are exceptional arrays 1 - zeroes, ones, empty array, identity array.. Follow below:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#above is floating point.. if u check the datatype it'll show being float

In [26]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.eye(5) #eye is used to create the identity array.. 5 used is all these is the shape of the array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.arange(5,50,2) # 5 is the starting point, 50 - stop poing, 2- spacing

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [33]:
# List : ordered and changeable. Allows duplicate members
# Tuple : ordered and unchangeable. Allows duplicate members
# Sets  : unordered and unindexed. No duplicate members
# Dictionaries: unordered, changeable and indexed. No duplicate members ---  in dictionaries instead of int indexing label indexing happens here

In [1]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

In [3]:
for x in thisdict.keys():
    print(x, thisdict.values())

brand dict_values(['Ford', 'Mustang', 1964])
model dict_values(['Ford', 'Mustang', 1964])
year dict_values(['Ford', 'Mustang', 1964])
